/**
 * Regenerates `tests/stress.fixtures.ts`, the scale fixtures for the type-level
 * machinery: a wide tree (60 sections x 21 routes = 1,260 routes) and a deep
 * tree (30 nested levels). Deterministic — run it after changing the shapes:
 *
 *   node tests/generate-stress.mjs
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const SECTIONS = 60;
const CHILDREN = 4;
const GRANDCHILDREN = 4;
const DEPTH = 30;

const indent = (level) => '  '.repeat(level);

const wideSection = (s) => {
  const lines = [];
  const icon = s % 3 === 0 ? `, icon: 'star'` : '';
  lines.push(`${indent(1)}section${s}: {`);
  lines.push(`${indent(2)}_metadata: { title: 'Section ${s}'${icon} },`);

  for (let c = 1; c <= CHILDREN; c += 1) {
    const key = c === 1 ? `'[id]'` : `child${c}`;
    const title = c === 1 ? `Section ${s} detail` : `Section ${s} child ${c}`;
    lines.push(`${indent(2)}${key}: {`);
    lines.push(`${indent(3)}_metadata: { title: '${title}' },`);
    for (let g = 1; g <= GRANDCHILDREN; g += 1) {
      lines.push(`${indent(3)}leaf${g}: { _metadata: { title: '${title} leaf ${g}' } },`);
    }
    lines.push(`${indent(2)}},`);
  }

  lines.push(`${indent(1)}},`);
  return lines.join('\n');
};

const deepLevels = () => {
  const open = [];
  const close = [];
  for (let level = 1; level <= DEPTH; level += 1) {
    open.push(`${indent(level)}l${level}: {`);
    open.push(`${indent(level + 1)}_metadata: { title: 'Level ${level}' },`);
    close.unshift(`${indent(level)}},`);
  }
  return [...open, ...close].join('\n');
};

const file = `import { defineRoutes } from '@hyeonqyu/typed-router-core';

/**
 * Generated by \`node tests/generate-stress.mjs\` — do not edit by hand.
 *
 * Scale fixtures for the type-level machinery. \`stress.types.test-d.ts\` asserts
 * against them so that width (${SECTIONS * (1 + CHILDREN + CHILDREN * GRANDCHILDREN)} routes) and depth (${DEPTH} levels) keep
 * compiling; \`tsc --extendedDiagnostics -p tests/tsconfig.json\` is the tool for
 * comparing the cost before and after touching the machinery.
 */
export const wideRoutes = defineRoutes({
${Array.from({ length: SECTIONS }, (_, i) => wideSection(i + 1)).join('\n')}
});

export const deepRoutes = defineRoutes({
${deepLevels()}
});

export type WideRoutes = typeof wideRoutes;
export type DeepRoutes = typeof deepRoutes;
`;

const out = join(dirname(fileURLToPath(import.meta.url)), 'stress.fixtures.ts');
writeFileSync(out, file);
console.log(`wrote ${out}: ${SECTIONS * (1 + CHILDREN + CHILDREN * GRANDCHILDREN)} wide routes, ${DEPTH} deep levels`);
